# Generated by Django 5.2.5 on 2026-08-27 18:40

import django.core.validators
import django.db.models.deletion
import masiscam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('identificacion_cliente', models.CharField(blank=True, max_length=20)),
                ('responsable', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('ubicacion_maps', models.URLField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=12)),
                ('imagen_principal', models.ImageField(blank=True, upload_to='masiscam/proyectos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('drive_folder_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('drive_folder_url', models.URLField(blank=True, editable=False)),
                ('token_publico', models.CharField(default=masiscam.models.generar_token_publico, editable=False, max_length=64, unique=True)),
                ('pagina_publica_activa', models.BooleanField(default=False)),
                ('publicar_cliente', models.BooleanField(default=False)),
                ('publicar_ubicacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_masiscam_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_masiscam', to='accounts.empresa')),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'permissions': [('regenerar_token', 'Puede regenerar el token público MASISCAM')],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('numero_serie', models.CharField(blank=True, max_length=120)),
                ('ratio', models.CharField(blank=True, max_length=80)),
                ('potencia_hp', models.CharField(blank=True, max_length=80)),
                ('rpm', models.CharField(blank=True, max_length=80)),
                ('service_factor', models.CharField(blank=True, max_length=80)),
                ('rotacion', models.CharField(blank=True, max_length=80)),
                ('tipo_aceite', models.CharField(blank=True, max_length=180)),
                ('informacion_tecnica', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En mantenimiento')], default='ACTIVO', max_length=15)),
                ('fotografia_general', models.ImageField(blank=True, upload_to='masiscam/equipos/%Y/%m/')),
                ('fotografia_placa', models.ImageField(blank=True, upload_to='masiscam/placas/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('visible_publico', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='masiscam.proyecto')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('FOTOGRAFIAS', 'Fotografías'), ('PLACAS', 'Placas técnicas'), ('PLANOS', 'Planos'), ('MANUALES', 'Manuales'), ('FICHAS', 'Fichas técnicas'), ('CERTIFICADOS', 'Certificados'), ('INFORMES', 'Informes'), ('MANTENIMIENTOS', 'Mantenimientos'), ('GARANTIAS', 'Garantías'), ('ACTAS', 'Actas de entrega'), ('VIDEOS', 'Videos'), ('OTROS', 'Otros documentos')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='masiscam/documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'dwg', 'dxf', 'mp4', 'mov'])])),
                ('nombre_original', models.CharField(editable=False, max_length=255)),
                ('tipo_mime', models.CharField(editable=False, max_length=150)),
                ('tamano', models.PositiveBigIntegerField(default=0, editable=False)),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('drive_file_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('drive_view_url', models.URLField(blank=True, editable=False)),
                ('drive_download_url', models.URLField(blank=True, editable=False)),
                ('publico', models.BooleanField(default=False)),
                ('estado_sincronizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SUBIENDO', 'Subiendo'), ('SINCRONIZADO', 'Sincronizado'), ('ERROR', 'Error'), ('ARCHIVADO', 'Archivado')], default='PENDIENTE', max_length=15)),
                ('error_sincronizacion', models.TextField(blank=True, editable=False)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_masiscam', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='masiscam.equipo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='masiscam.proyecto')),
            ],
            options={
                'ordering': ['-cargado_en'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('objeto_tipo', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=80)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_masiscam', to='accounts.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='masiscam.proyecto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RolMasiscam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador MASISCAM'), ('TECNICO', 'Técnico'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_masiscam', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'rol MASISCAM',
                'permissions': [('archivar_proyecto', 'Puede archivar proyectos MASISCAM'), ('administrar_equipos', 'Puede administrar equipos MASISCAM'), ('subir_documentos', 'Puede subir documentos MASISCAM'), ('reemplazar_documentos', 'Puede reemplazar o archivar documentos MASISCAM'), ('generar_qr', 'Puede generar y descargar QR MASISCAM'), ('configurar_visibilidad', 'Puede configurar visibilidad pública MASISCAM'), ('ver_historial', 'Puede ver historial MASISCAM')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='masiscam_proyecto_codigo_empresa_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_sincronizacion__in', ['PENDIENTE', 'SUBIENDO', 'SINCRONIZADO'])), fields=('proyecto', 'hash_sha256'), name='masiscam_documento_hash_activo_uniq'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['empresa', '-creado_en'], name='masiscam_au_empresa_6f7aed_idx'),
        ),
    ]
