# Generated by Django 5.2.5 on 2026-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='publicar_descripcion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='publicar_equipos',
            field=models.BooleanField(default=True),
        ),
    ]
