# Generated by Django 5.2.5 on 2026-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0006_registroequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroequipo',
            name='tipo',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('ASISTENCIA', 'Asistencia'), ('GARANTIA', 'Garantía'), ('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación')], max_length=13),
        ),
    ]
