# Generated by Django 5.2.17 on 2026-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0009_rolmasiscam_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo_producto',
            field=models.CharField(choices=[('REDUCTOR', 'Reductores'), ('BOMBA', 'Bombas')], default='REDUCTOR', editable=False, max_length=32),
        ),
    ]
