# Generated by Django 6.1.1 on 2026-09-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0009_alter_equipo_tipo_producto'),
        ('masiscam', '0009_rolmasiscam_cliente'),
    ]

    operations = [
    ]
