# Generated by Django 5.2.17 on 2026-09-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0010_alter_equipo_tipo_producto'),
        ('masiscam', '0010_merge_20260922_2021'),
    ]

    operations = [
    ]
