# Generated by Django 5.2.17 on 2026-09-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0011_merge_20260924_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolmasiscam',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceso_usuario', to='masiscam.cliente'),
        ),
    ]
