# Generated by Django 5.2.17 on 2026-10-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0012_cliente_varios_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano', models.PositiveBigIntegerField()),
                ('hash_sha256', models.CharField(max_length=64)),
                ('drive_file_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DISPONIBLE', 'Disponible'), ('ERROR', 'Error de carga')], default='PENDIENTE', max_length=12)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='registroequipo',
            name='secuencia',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='registroequipo',
            constraint=models.UniqueConstraint(fields=('equipo', 'tipo', 'secuencia'), name='masiscam_registro_secuencia_uniq'),
        ),
        migrations.AddField(
            model_name='archivoregistro',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='masiscam.registroequipo'),
        ),
        migrations.AddConstraint(
            model_name='archivoregistro',
            constraint=models.UniqueConstraint(fields=('registro', 'hash_sha256'), name='masiscam_archivo_registro_hash_uniq'),
        ),
    ]
