# Generated by Django 5.2.17 on 2026-10-02 14:00

from django.db import migrations


def numerar_por_fecha(apps, schema_editor):
    Registro = apps.get_model("masiscam", "RegistroEquipo")
    registros = Registro.objects.using(schema_editor.connection.alias)
    for equipo, tipo in registros.order_by().values_list("equipo_id", "tipo").distinct():
        grupo = registros.filter(equipo_id=equipo, tipo=tipo)
        ids = list(grupo.order_by("fecha", "pk").values_list("pk", flat=True))
        grupo.update(secuencia=None)
        for numero, pk in enumerate(ids, 1):
            registros.filter(pk=pk).update(secuencia=numero)


class Migration(migrations.Migration):

    dependencies = [
        ('masiscam', '0013_archivos_registro_y_secuencia'),
    ]

    operations = [
        migrations.RunPython(numerar_por_fecha, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='registroequipo',
            options={'ordering': ['fecha', 'pk']},
        ),
    ]
