"""Browser regressions for private dialogs; called with a disposable database."""
from playwright.sync_api import expect
from unittest.mock import patch


def verify(page, base, width, output):
    page.goto(base + '/app/cuentas/login/')
    page.fill('#id_username', 'QA.MASISCAM')
    page.fill('#id_password', 'QA-only-password-123')
    page.get_by_role('button', name='Ingresar', exact=True).click()
    page.wait_for_url(base + '/app/')
    modal = page.locator('#masiscamFormModal')
    expect(modal).not_to_be_visible()
    if width < 992:
        menu = page.get_by_role('button', name='Menú', exact=True)
        menu.click()
        expect(page.locator('#appMenu')).to_be_visible()
        expect(page.locator('#appMenu')).to_have_class('app-menu collapse show')
        menu.click()
        expect(page.locator('#appMenu')).not_to_be_visible()
    else:
        expect(page.locator('.app-menu-toggle')).not_to_be_visible()
    page.goto(base + '/app/clientes/')
    create = page.get_by_role('link', name='Crear cliente', exact=True)
    for close in ('Cancelar', 'Cerrar', 'Escape'):
        create.click()
        expect(modal.locator('#id_nombre_comercial')).to_be_visible()
        if close == 'Escape':
            page.keyboard.press('Escape')
        else:
            modal.get_by_role('button', name=close, exact=True).click()
        expect(modal).not_to_be_visible()
    create.click()
    expect(modal.locator('#id_nombre_comercial')).to_be_visible()
    modal.locator('form').evaluate('form => form.noValidate = true')
    modal.get_by_role('button', name='Guardar', exact=True).click()
    expect(modal.locator('.masiscam-form-modal__status')).to_contain_text('Revisa')
    modal.locator('#id_nombre_comercial').fill(f'Cliente modal {width}')
    modal.locator('#id_ruc').fill(f'099000{width:04d}001')
    modal.locator('#id_razon_social').fill('Cliente de prueba')
    modal.get_by_role('button', name='Guardar', exact=True).click()
    expect(modal).not_to_be_visible()
    expect(page.locator('table')).to_contain_text(f'Cliente modal {width}')
    page.goto(base + '/app/productos/reductor/')
    page.get_by_role('link', name='Crear reductor').click()
    expect(modal.locator('#id_ruc')).to_be_visible()
    modal.locator('#id_ruc').fill(f'098000{width:04d}001')
    modal.locator('#cliente-crear').click()
    child = page.locator('#cliente-modal')
    expect(child).to_be_visible()
    child.locator('#cliente-modal-cerrar').click()
    expect(child).not_to_be_visible()
    modal.locator('#cliente-crear').click()
    child.locator('#id_nuevo-nombre_comercial').fill(f'Cliente anidado {width}')
    child.locator('#id_nuevo-razon_social').fill('Cliente anidado')
    child.get_by_role('button', name='Guardar y seleccionar').click()
    expect(child).not_to_be_visible()
    expect(modal.locator('#cliente-nombre')).to_have_value(f'Cliente anidado {width}')
    modal.get_by_role('button', name='Guardar reductor').click()
    expect(modal.locator('.masiscam-form-modal__status')).to_contain_text('Revisa')
    expect(modal.locator('#cliente-nombre')).to_have_value(f'Cliente anidado {width}')
    for field, value in {'camaronera': 'QA', 'estacion': 'E1', 'sector': 'S1', 'numero_equipo': f'MODAL-{width}', 'marca': 'Marca', 'modelo': 'M1', 'numero_serie': f'MODAL-{width}', 'potencia': '20 HP'}.items():
        modal.locator('#id_' + field).fill(value)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1')
    assert page.evaluate('''() => {const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.length===new Set(ids).size}''')
    page.screenshot(path=str(output / f'private-modal-{width}.png'))
    with patch('masiscam.signals.encolar_carpeta_equipo'):
        modal.get_by_role('button', name='Guardar reductor').click()
        expect(modal).not_to_be_visible()
    page.locator('tr').filter(has_text=f'MODAL-{width}').get_by_role('link', name='Ver ficha').click()
    page.get_by_role('button', name='Agregar registro').click()
    registro = page.locator('#registro-modal')
    registro.get_by_role('button', name='Cancelar', exact=True).click()
    expect(registro).not_to_be_visible()
    page.get_by_role('button', name='Agregar registro').click()
    registro.locator('#id_observacion').fill(f'Observacion QA {width}')
    registro.locator('#id_tipo').select_option(index=1)
    registro.get_by_role('button', name='Guardar', exact=True).click()
    expect(registro).not_to_be_visible()
    from masiscam.models import RegistroEquipo
    assert RegistroEquipo.objects.filter(observacion=f'Observacion QA {width}').exists()
    from django.db import connections
    connections.close_all()
    page.goto(base + '/app/proyectos/')
    page.get_by_role('link', name='Nuevo proyecto').click()
    expect(modal.locator('form')).to_be_visible()
    modal.get_by_role('button', name='Guardar', exact=True).click()
    expect(modal.locator('.masiscam-form-modal__status')).to_contain_text('Revisa')
    modal.get_by_role('button', name='Cancelar', exact=True).click()
    page.get_by_role('link', name='Nuevo proyecto').click()
    for field, value in {'codigo': f'QA-{width}', 'nombre': f'Proyecto modal {width}', 'cliente': 'Cliente QA', 'responsable': 'QA', 'fecha_inicio': '2026-09-21'}.items():
        modal.locator('#id_' + field).fill(value)
    modal.get_by_role('button', name='Guardar', exact=True).click()
    expect(modal).not_to_be_visible()
    expect(page.locator('table')).to_contain_text(f'Proyecto modal {width}')
    page.locator('table a').first.click()
    for target in ('equipoForm', 'documentoForm'):
        button = page.locator(f'[data-bs-target="#{target}"]')
        button.click()
        expect(page.locator('#' + target)).to_be_visible()
        expect(page.locator('#' + target)).to_have_class('collapse show')
        expect(modal).not_to_be_visible()
        button.click()
        expect(page.locator('#' + target)).not_to_be_visible()
    assert page.locator('.app-brand img').evaluate("img => img.complete && img.naturalWidth > 0 && getComputedStyle(img).backgroundColor === 'rgba(0, 0, 0, 0)'")
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1')
    page.screenshot(path=str(output / f'private-tables-{width}.png'), full_page=True)
